### ISSUE TITLE
Hover tag not working

### ISSUE THREAD

**Issue by char1129** [char1129/navigation-highlight#1]
@thomasjbradley @char1129 

Good morning/evening Professor Thomas,

Would you mind looking over my css file to tell me why my active and hover tags aren't working?
main.css is the file I was tinkering with to see if I could get it to work after following your video on line.
main2.css is a duplicate of my original code that has a working active tag (I am unsure how I made it work) and a hover tag that doesn't. 
(You may also notice there are two index files, index.html and index2.html. If you are wanting to test it my css against the html.)
The css and index names co-relate with one another.
main.css works with index.html. (Files being tinkered with to get the tags to work. Active and hover tags not working.)
main2.css works with index2.html. (Original code duplicates. Just hover tag not working.)

I'd appreciate if you could point me in the right direction on how I could go about to make either one of these files work? The files satisfy ever requirement Markbot wants but the hover in main2/index2 files.

*Please note I accidentally rotated a screen capture page again... I will notify you once I am able to submit through Markbot of my blunder, if it assumes it to be cheating.* 

Thank you!

Sarah

**Comment by thomasjbradley** [comment]
In the CSS, on this line:
https://github.com/char1129/navigation-highlight/blob/gh-pages/css/main.css#L52
You don’t need to specify `a` because the `.current` *is* an `<a>` tag.

**Comment by thomasjbradley** [comment]
The hover seems to be working in both. Did you figure that out?

**Comment by char1129** [comment]
The problem must of been with Chrome! I did try it out on Firefox earlier and it wasn't working, but now it seems to be! I guess I just have the current tag to work on. Thank you!

**Comment by char1129** [comment]
@char1129 @thomasjbradley You're right the hover tag works but .current doesn't. I've been trying to figure out by reading about the tag online and trying to see if adding the whole button css to the tag would work and it hasn't. I've also moved the .current tag around a bit to see if the sequence helps, but trying to keep it below .buttons css to keep the flow.

**Comment by char1129** [comment]
Figured it out! Posting new issue with Markbot not accepting the finished product.
