### ISSUE TITLE
Markbot not accepting highlights (cannot submit)

### ISSUE THREAD

**Issue by char1129** [char1129/navigation-highlight#2]
@thomasjbradley
I figured out my highlighting issue to be browser confusion in reading the code of .button classes on 'a' tags. Took off .button from the 'a' tag on line 38 and it all magically works. 
Markbot still thinks highlighting is still not occurring, but it is and I cannot submit.

If you don't mind taking a look, I'd appreciate it... 

I am using the .current attribute the same way you showed in your video example. 
Example:

html
<__a class="current" href="#">Home<__/a>
css
.current {
background-color: #b20953;
}

**Comment by char1129** [comment]
Going to troubleshoot this after I complete/work on the other part of this assignment. Will reopen if I cannot figure it out.

**Comment by thomasjbradley** [comment]
👍
